/** @type {import('tailwindcss').Config} */
export default {
  darkMode: 'class',
  content: ['./index.html', './src/**/*.{js,jsx}'],
  theme: {
    extend: {
      colors: {
        'surface-container-highest': '#d3e4fe',
        'secondary-container': '#86f2e4',
        'on-tertiary-fixed-variant': '#7f2b00',
        'primary-fixed-dim': '#b0c9e8',
        'on-secondary-container': '#006f66',
        'on-tertiary-container': '#f35e15',
        'primary-container': '#0f2942',
        'on-primary-fixed': '#011d35',
        'surface-dim': '#cbdbf5',
        'on-tertiary-fixed': '#370e00',
        tertiary: '#290800',
        'surface-bright': '#f8f9ff',
        'tertiary-container': '#4b1600',
        'on-primary-container': '#7991af',
        'tertiary-fixed': '#ffdbce',
        outline: '#74777e',
        'on-primary-fixed-variant': '#314863',
        'surface-container-high': '#dce9ff',
        'on-background': '#0b1c30',
        secondary: '#006a61',
        'surface-variant': '#d3e4fe',
        'on-surface-variant': '#43474d',
        background: '#f8f9ff',
        'inverse-on-surface': '#eaf1ff',
        'on-primary': '#ffffff',
        'on-surface': '#0b1c30',
        'on-error-container': '#93000a',
        'surface-tint': '#49607c',
        'on-secondary-fixed-variant': '#005049',
        'surface-container': '#e5eeff',
        primary: '#001428',
        surface: '#f8f9ff',
        'on-tertiary': '#ffffff',
        'outline-variant': '#c3c6ce',
        'inverse-surface': '#213145',
        error: '#ba1a1a',
        'surface-container-lowest': '#ffffff',
        'surface-container-low': '#eff4ff',
        'on-secondary-fixed': '#00201d',
        'on-secondary': '#ffffff',
        'inverse-primary': '#b0c9e8',
        'on-error': '#ffffff',
        'primary-fixed': '#d1e4ff',
        'tertiary-fixed-dim': '#ffb599',
        'error-container': '#ffdad6',
        'secondary-fixed': '#89f5e7',
        'secondary-fixed-dim': '#6bd8cb',
      },
      borderRadius: {
        DEFAULT: '0.25rem',
        lg: '0.5rem',
        xl: '0.75rem',
        full: '9999px',
      },
      spacing: {
        'space-3xl': '4rem',
        'gutter-mobile': '1rem',
        'container-max': '76rem',
        'space-xs': '0.5rem',
        'space-2xl': '3rem',
        'gutter-desktop': '1.5rem',
        'space-2xs': '0.25rem',
        'space-lg': '1.5rem',
        'space-sm': '0.75rem',
        'space-md': '1rem',
        'space-xl': '2rem',
      },
      maxWidth: {
        'container-max': '76rem',
      },
      fontFamily: {
        'label-sm': ['Inter', 'sans-serif'],
        'headline-lg-mobile': ['Plus Jakarta Sans', 'sans-serif'],
        'body-lg': ['Inter', 'sans-serif'],
        'body-sm': ['Inter', 'sans-serif'],
        'headline-sm': ['Plus Jakarta Sans', 'sans-serif'],
        'display-lg-mobile': ['Plus Jakarta Sans', 'sans-serif'],
        'headline-md': ['Plus Jakarta Sans', 'sans-serif'],
        'body-md': ['Inter', 'sans-serif'],
        'label-md': ['Inter', 'sans-serif'],
        'display-lg': ['Plus Jakarta Sans', 'sans-serif'],
        'label-lg': ['Inter', 'sans-serif'],
        'headline-lg': ['Plus Jakarta Sans', 'sans-serif'],
        'metric-mono': ['Inter', 'sans-serif'],
      },
      fontSize: {
        'label-sm': ['11px', { lineHeight: '14px', letterSpacing: '0.04em', fontWeight: '600' }],
        'headline-lg-mobile': ['22px', { lineHeight: '28px', letterSpacing: '-0.01em', fontWeight: '700' }],
        'body-lg': ['16px', { lineHeight: '24px', fontWeight: '400' }],
        'body-sm': ['12px', { lineHeight: '16px', fontWeight: '400' }],
        'headline-sm': ['16px', { lineHeight: '22px', fontWeight: '600' }],
        'display-lg-mobile': ['30px', { lineHeight: '36px', letterSpacing: '-0.015em', fontWeight: '700' }],
        'headline-md': ['20px', { lineHeight: '26px', letterSpacing: '-0.005em', fontWeight: '600' }],
        'body-md': ['14px', { lineHeight: '20px', fontWeight: '400' }],
        'label-md': ['12px', { lineHeight: '16px', letterSpacing: '0.02em', fontWeight: '600' }],
        'display-lg': ['40px', { lineHeight: '48px', letterSpacing: '-0.02em', fontWeight: '700' }],
        'label-lg': ['14px', { lineHeight: '18px', letterSpacing: '0.01em', fontWeight: '600' }],
        'headline-lg': ['28px', { lineHeight: '34px', letterSpacing: '-0.01em', fontWeight: '700' }],
        'metric-mono': ['13px', { lineHeight: '16px', letterSpacing: '-0.01em', fontWeight: '500' }],
      },
    },
  },
  plugins: [],
}
